package vvg_upup.jbpm_oms;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Djelatnik implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(generator = "DJELATNIK_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(name = "DJELATNIK_ID_GENERATOR", sequenceName = "DJELATNIK_ID_SEQ")
    private java.lang.Long id;

    public Djelatnik() {
    }
    
    public Djelatnik(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }

}