package vvg_upup.jbpm_oms;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Login implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Korisnicko ime")
   private java.lang.String korisnickoIme;
   @org.kie.api.definition.type.Label("Zaporka")
   private java.lang.String zaporka;

   private java.lang.Long IDprijava;

   public Login()
   {
   }

   public java.lang.String getKorisnickoIme()
   {
      return this.korisnickoIme;
   }

   public void setKorisnickoIme(java.lang.String korisnickoIme)
   {
      this.korisnickoIme = korisnickoIme;
   }

   public java.lang.String getZaporka()
   {
      return this.zaporka;
   }

   public void setZaporka(java.lang.String zaporka)
   {
      this.zaporka = zaporka;
   }

   public java.lang.Long getIDprijava()
   {
      return this.IDprijava;
   }

   public void setIDprijava(java.lang.Long IDprijava)
   {
      this.IDprijava = IDprijava;
   }

   public Login(java.lang.String korisnickoIme, java.lang.String zaporka,
         java.lang.Long IDprijava)
   {
      this.korisnickoIme = korisnickoIme;
      this.zaporka = zaporka;
      this.IDprijava = IDprijava;
   }

}