package vvg_upup.jbpm_oms;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Lokacija implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long IDlokacija;
   @org.kie.api.definition.type.Label(value = "Mjesto")
   private java.lang.String mjesto;
   @org.kie.api.definition.type.Label(value = "Ulica")
   private java.lang.String ulica;
   @org.kie.api.definition.type.Label(value = "Kucni broj")
   private java.lang.String kucniBroj;
   @org.kie.api.definition.type.Label(value = "Kat")
   private java.lang.String kat;
   @org.kie.api.definition.type.Label(value = "Prostorija")
   private java.lang.String prostorija;
   @org.kie.api.definition.type.Label(value = "Bar kod lokacije")
   private java.lang.String barCodLokacija;

   public Lokacija()
   {
   }

   public java.lang.Long getIDlokacija()
   {
      return this.IDlokacija;
   }

   public void setIDlokacija(java.lang.Long IDlokacija)
   {
      this.IDlokacija = IDlokacija;
   }

   public java.lang.String getMjesto()
   {
      return this.mjesto;
   }

   public void setMjesto(java.lang.String mjesto)
   {
      this.mjesto = mjesto;
   }

   public java.lang.String getUlica()
   {
      return this.ulica;
   }

   public void setUlica(java.lang.String ulica)
   {
      this.ulica = ulica;
   }

   public java.lang.String getKucniBroj()
   {
      return this.kucniBroj;
   }

   public void setKucniBroj(java.lang.String kucniBroj)
   {
      this.kucniBroj = kucniBroj;
   }

   public java.lang.String getKat()
   {
      return this.kat;
   }

   public void setKat(java.lang.String kat)
   {
      this.kat = kat;
   }

   public java.lang.String getProstorija()
   {
      return this.prostorija;
   }

   public void setProstorija(java.lang.String prostorija)
   {
      this.prostorija = prostorija;
   }

   public java.lang.String getBarCodLokacija()
   {
      return this.barCodLokacija;
   }

   public void setBarCodLokacija(java.lang.String barCodLokacija)
   {
      this.barCodLokacija = barCodLokacija;
   }

   public Lokacija(java.lang.Long IDlokacija, java.lang.String mjesto,
         java.lang.String ulica, java.lang.String kucniBroj,
         java.lang.String kat, java.lang.String prostorija,
         java.lang.String barCodLokacija)
   {
      this.IDlokacija = IDlokacija;
      this.mjesto = mjesto;
      this.ulica = ulica;
      this.kucniBroj = kucniBroj;
      this.kat = kat;
      this.prostorija = prostorija;
      this.barCodLokacija = barCodLokacija;
   }

}