package vvg_upup.jbpm_oms;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OdabirModula implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Odabir modula")
   private java.lang.String odabirModula;

   public OdabirModula()
   {
   }

   public java.lang.String getOdabirModula()
   {
      return this.odabirModula;
   }

   public void setOdabirModula(java.lang.String odabirModula)
   {
      this.odabirModula = odabirModula;
   }

   public OdabirModula(java.lang.String odabirModula)
   {
      this.odabirModula = odabirModula;
   }

}