package vvg_upup.jbpm_oms;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Odabir implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Odabir")
   private java.lang.String odabir;

   public Odabir()
   {
   }

   public java.lang.String getOdabir()
   {
      return this.odabir;
   }

   public void setOdabir(java.lang.String odabir)
   {
      this.odabir = odabir;
   }

   public Odabir(java.lang.String odabir)
   {
      this.odabir = odabir;
   }

}