package vvg_upup.jbpm_oms;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Razduzenje implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Razduzenje() {
    }

}