package vvg_upup.jbpm_oms;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Razduzenje implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long IDrazduzenje;
   @org.kie.api.definition.type.Label("Datum")
   private java.util.Date datum;

   @org.kie.api.definition.type.Label(value = "Bar Code sredstva")
   private java.lang.String barCode;

   @org.kie.api.definition.type.Label(value = "OIB djelatnika")
   private java.lang.String OIBdjelatnika;

   @org.kie.api.definition.type.Label(value = "Bar Code lokacije")
   private java.lang.String barCodLokacija;

   public Razduzenje()
   {
   }

   public java.lang.Long getIDrazduzenje()
   {
      return this.IDrazduzenje;
   }

   public void setIDrazduzenje(java.lang.Long IDrazduzenje)
   {
      this.IDrazduzenje = IDrazduzenje;
   }

   public java.util.Date getDatum()
   {
      return this.datum;
   }

   public void setDatum(java.util.Date datum)
   {
      this.datum = datum;
   }

   public java.lang.String getBarCode()
   {
      return this.barCode;
   }

   public void setBarCode(java.lang.String barCode)
   {
      this.barCode = barCode;
   }

   public java.lang.String getOIBdjelatnika()
   {
      return this.OIBdjelatnika;
   }

   public void setOIBdjelatnika(java.lang.String OIBdjelatnika)
   {
      this.OIBdjelatnika = OIBdjelatnika;
   }

   public java.lang.String getBarCodLokacija()
   {
      return this.barCodLokacija;
   }

   public void setBarCodLokacija(java.lang.String barCodLokacija)
   {
      this.barCodLokacija = barCodLokacija;
   }

   public Razduzenje(java.lang.Long IDrazduzenje, java.util.Date datum,
         java.lang.String barCode, java.lang.String OIBdjelatnika,
         java.lang.String barCodLokacija)
   {
      this.IDrazduzenje = IDrazduzenje;
      this.datum = datum;
      this.barCode = barCode;
      this.OIBdjelatnika = OIBdjelatnika;
      this.barCodLokacija = barCodLokacija;
   }

}