package vvg_upup.jbpm_oms;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Razduzenje implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long IDrazduzenje;
   @org.kie.api.definition.type.Label(value = "Id sredstva")
   private java.lang.Long sredstvoID;
   @org.kie.api.definition.type.Label(value = "ID djelatnika")
   private java.lang.Long djelatnikID;
   @org.kie.api.definition.type.Label(value = "ID lokacije")
   private java.lang.Long lokacijaID;
   @org.kie.api.definition.type.Label(value = "Datum")
   private java.util.Date datum;

   public Razduzenje()
   {
   }

   public java.lang.Long getIDrazduzenje()
   {
      return this.IDrazduzenje;
   }

   public void setIDrazduzenje(java.lang.Long IDrazduzenje)
   {
      this.IDrazduzenje = IDrazduzenje;
   }

   public java.lang.Long getSredstvoID()
   {
      return this.sredstvoID;
   }

   public void setSredstvoID(java.lang.Long sredstvoID)
   {
      this.sredstvoID = sredstvoID;
   }

   public java.lang.Long getDjelatnikID()
   {
      return this.djelatnikID;
   }

   public void setDjelatnikID(java.lang.Long djelatnikID)
   {
      this.djelatnikID = djelatnikID;
   }

   public java.lang.Long getLokacijaID()
   {
      return this.lokacijaID;
   }

   public void setLokacijaID(java.lang.Long lokacijaID)
   {
      this.lokacijaID = lokacijaID;
   }

   public java.util.Date getDatum()
   {
      return this.datum;
   }

   public void setDatum(java.util.Date datum)
   {
      this.datum = datum;
   }

   public Razduzenje(java.lang.Long IDrazduzenje, java.lang.Long sredstvoID,
         java.lang.Long djelatnikID, java.lang.Long lokacijaID,
         java.util.Date datum)
   {
      this.IDrazduzenje = IDrazduzenje;
      this.sredstvoID = sredstvoID;
      this.djelatnikID = djelatnikID;
      this.lokacijaID = lokacijaID;
      this.datum = datum;
   }

}